### ISSUE TITLE
RRDtool

### ISSUE THREAD

**Issue by incmve** [Juerd/kWh#1]
Hi,

Leuk projekt maar klopt het dat er iets mist?
<code>cat /dev/ttyUSB0 | awk '{ print $0 > "/dev/stderr"; if (/^Cycle/) { print "update kWh.rrd N:" $5 } }' | rrdtool </code>

rrdtools moet nog wat er achter hebben toch?

**Comment by Juerd** [comment]
incmve skribis 2015-02-10  5:11 (-0800):

> Leuk projekt maar klopt het dat er iets mist?
> <code>cat /dev/ttyUSB0 | awk '{ print $0 > "/dev/stderr"; if
> (/^Cycle/) { print "update kWh.rrd N:" $5 } }' | rrdtool </code>
> rrdtools moet nog wat er achter hebben toch?

In je copy/paste ben je de "-" na rrdtool vergeten. Die geeft aan dat de

## commando's van stdin komen, niet op de command line.

Met vriendelijke groet, // Kind regards, // Korajn salutojn,

Juerd Waalboer  juerd@tnx.nl
TNX

**Comment by incmve** [comment]
Thats it? lol okay vanavond weer eens proberen.
Bedankt!

**Comment by incmve** [comment]
Hoi Juerd, nog een klein (dom)vraagje.
Ik heb alles zo'n beetje draaien maar ik probeer uit te vogelen hoe die threshold werkt.
Mijn kwh meter is 600 omw/kwh en ik wil hem op 6% zetten maar ik zien niet wat ik dan moet aanpassen in de code, kan jij me op weg helpen?

thanks!

Marcel

**Comment by Juerd** [comment]
incmve skribis 2015-02-13  9:42 (-0800):

> Ik heb alles zo'n beetje draaien maar ik probeer uit te vogelen hoe
> die threshold werkt.

Er zijn twee drempelwaardes: LO en HI, beide uitgedrukt in procenten
t.o.v. het gemiddelde.

LO geeft aan wanneer het zwarte streepje van de draaischijf is afgelopen.
HI geeft aan wanneer het zwarte streepje van de draaischijf is begonnen.

LO zet je op een waarde LAGER DAN de laagste waarde van tijdens het zwarte
streepje.
HI zet je op een waarde HOGER DAN de hoogste waarde die in de rest van
de draaischijf voorkomt.

> Mijn kwh meter is 600 omw/kwh en ik wil hem op 6% zetten maar ik zien
> niet wat ik dan moet aanpassen in de code, kan jij me op weg helpen?

Dat kan ik, maar dat wil ik niet. Als je dit niet zelf kunt uitvogelen,
mis je de benodigde basiskennis om hier onbegeleid mee aan de slag te
gaan. Het is geen product voor eindgebruikers.

Dat doe ik niet om lullig te doen, maar omdat ik veel vragen om hulp
krijg, en daarom duidelijk mijn grenzen wil aangeven om het voor mezelf
ook leuk te houden.

Alle informatie die ik beschikbaar stel staat op

## http://juerd.nl/site.plp/kwh en https://github.com/Juerd/kWh

Met vriendelijke groet, // Kind regards, // Korajn salutojn,

Juerd Waalboer  juerd@tnx.nl
TNX

**Comment by incmve** [comment]
Misschien is het een idee je site aan te passen want daar zeg je 

> Hopelijk worden nu alle vragen in één keer beantwoord! (Zo niet, mail me dan gerust.)

Ik begrijp hoe arduino werk etc dus volgens mij is dat basis kennis, ik vroeg alleen een pointer in de juiste richting.
Alle respect voor je grenzen en heel begrijpelijk als je dat aangeeft maar het stukje  

>  mis je de benodigde basiskennis om hier onbegeleid mee aan de slag te
> gaan. Het is geen product voor eindgebruikers.

Was misschien wat overbodig

**Comment by Juerd** [comment]
incmve skribis 2015-02-14  1:04 (-0800):

> Misschien is het een idee je site aan te passen want daar zeg je 
> 
> > Hopelijk worden nu alle vragen in ��n keer beantwoord! (Zo niet,
> > mail me dan gerust.)

Daar heb je een punt. Mijn vorige bericht was onaardig, sorry daarvoor.

> Ik begrijp hoe arduino werk etc dus volgens mij is dat basis kennis,
> ik vroeg alleen een pointer in de juiste richting.

Je gaf aan niet te kunnen vinden hoe je 1 waarde aanpast. 

Dat doe je met de knopjes van de TM1638-module, of door de waarde in
read_settings aan te passen. Welk knopje wat doet, vind je in regel 10

## t/m 17 en 120 t/m 127.

Met vriendelijke groet, // Kind regards, // Korajn salutojn,

Juerd Waalboer  juerd@tnx.nl
TNX

**Comment by incmve** [comment]
ik krijg waardes terug die redelijk in de buurt komen, kwestie van finetunen dus. Bedankt!
